global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-app"
    static_configs:
      - targets: ["node-app:9615"]
    relabel_configs:
      - source_labels: [__address__]
        regex: '^(.+):\d+$'
        target_label: "container_name"
        replacement: "${1}"
    metric_relabel_configs:
      - regex: "(name|pid|pm_id|hostname)"
        action: "labeldrop"

  - job_name: "my_app_metrics"
    static_configs:
      - targets: ["node-app:3001"]
    metrics_path: "/metrics"
