server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: node_app
    static_configs:
      - targets:
          - node-app
        labels:
          job: varlogs
          __path__: /var/log/node-app.log
      - targets:
          - node-app
        labels:
          job: console.logs
          __path__: /var/log/console.log
